@startuml arquitectura
skinparam dpi 170
skinparam componentStyle rectangle
skinparam defaultFontSize 12
actor "Portal Web (INT-02)" as Portal
node "Pedidos, Logistica, Catalogo,\nPagos, Analitica, Notificaciones\n(INT-03 a INT-05)" as Mods
package "Modulo Usuarios y Autenticacion (ar.edu.uade.api.deliverygo.usuarios)" {
  [security + config\nJwtAuthFilter, JwtProvider,\nSecurityConfig] as Sec
  [controller\nUsuarioController, AuthController,\nDireccionController] as Ctrl
  [service\nUsuarioService, AuthService,\nDireccionService] as Srv
  [repository\nUsuarioRepository, RolRepository,\nDireccionRepository] as Rep
  [integration\nNotificacionesClient] as Int
  [dto + mapper] as Dto
  [domain\nUsuario, Rol, Direccion] as Model
}
database "BD Usuarios\n(propia, DM-11)" as BD
node "Notificaciones\n(INT-01)" as Notif
Portal --> Sec : HTTP/JSON
Mods --> Sec : HTTP/JSON
Sec --> Ctrl
Ctrl --> Srv
Ctrl ..> Dto
Srv --> Rep
Srv --> Int
Rep --> Model
Rep --> BD
Int --> Notif : HTTP/JSON (mock en Etapa 2)
@enduml
